spring.application.name=RISKOR_DevTeam
server.port=${PORT:8080}
server.servlet.context-path=/

spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=${BD_DRIVER}

#Codificación UTF-8 (evita problemas con acentos (á, ú, etc), ñ, etc)
# Ahorrando problemas de interpretación en solicitudes que contengan carácteres especiales - Recomendado debido al uso de español
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

#Misma config para los servlet (Controlador que maneja las solicitudes HTTP)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#Configuración clave para hacer uso de Cloudinary (Imágenes y Documentos)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#Configuración clave para envío de correos
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

#En producción agregar variables de entorno
SALT=${SALT}

#Clave secreta para HS256
security.jwt.secret=${SECRET_KEY_JWT}

#Mencionamos cuál es el emisor del JWT
security.jwt.issuer=${SECURITY_JWT_ISSUER}

#Tiempo de vida de nuestro token (Milisegundos)
security.jwt.expiration=${JWT_EXPIRATION}