spring.application.name=RISKOR_DevTeam
server.port=${PORT:8080}
#Establece que la api sea accesible desde la raíz para el servidor
server.servlet.context-path=/

spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}
spring.datasource.driver-class-name=${BD_DRIVER}

#Configuración clave para hacer uso de Cloudinary (Imágenes y Documentos)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

#Configuración clave para envío de correos
spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

#Propiedad personalizada para crear una contraseña segura
SALT=${SALT}

#Clave secreta para HS256
security.jwt.secret=${SECRET_KEY_JWT}

#Mencionamos cuál es el emisor del JWT
security.jwt.issuer=${SECURITY_JWT_ISSUER}

#Tiempo de vida de nuestro token (Milisegundos)
security.jwt.expiration=${JWT_EXPIRATION}

#Solo se podrán realizar 3 conexiones a la DB de manera simultanea
spring.datasource.hikari.maximum-pool-size=3
#Tiempo de espera para las conexiones, si sobrepasa 30 segundos dará excepción una solicitud
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.connectionInitSql=ALTER SESSION DISABLE PARALLEL DML